services:
  ziad-curl:
    build: .
    container_name: ziad-curl
    restart: unless-stopped

    environment:
      - PORT=8080

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"

      - "traefik.http.routers.ziad-curl-http.rule=Host(`ziadelshahawy.dev`) && HeadersRegexp(`User-Agent`, `(?i).*curl.*`)"
      - "traefik.http.routers.ziad-curl-http.entrypoints=web"
      - "traefik.http.routers.ziad-curl-http.priority=100"
      - "traefik.http.routers.ziad-curl-http.service=ziad-curl"

      - "traefik.http.routers.ziad-curl-https.rule=Host(`ziadelshahawy.dev`) && HeadersRegexp(`User-Agent`, `(?i).*curl.*`)"
      - "traefik.http.routers.ziad-curl-https.entrypoints=websecure"
      - "traefik.http.routers.ziad-curl-https.tls=true"
      - "traefik.http.routers.ziad-curl-https.tls.certresolver=myresolver"
      - "traefik.http.routers.ziad-curl-https.priority=100"
      - "traefik.http.routers.ziad-curl-https.service=ziad-curl"

      - "traefik.http.services.ziad-curl.loadbalancer.server.port=8080"

    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
